[package]
authors = ["Sergio Gasquez <sergio.gasquez@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name    = "crimpdeq"
version = "0.1.0"

[[bin]]
name = "crimpdeq"
path = "./src/bin/main.rs"

[dependencies]
bleps = { git = "https://github.com/bjoernQ/bleps", rev = "febf18abc4777b0227ef56b22aa6bcd78947fa24", package = "bleps", features = [
    "async",
    "defmt",
    "macros",
] }
bytemuck = "1.21.0"
bytemuck_derive = "1.8.1"
critical-section = "1.2.0"
defmt = "0.3.10"
defmt-rtt = "0.4.1"
embassy-executor = { version = "0.7.0", features = [
    "defmt",
    "task-arena-size-20480",
] }
embassy-sync = { version = "0.6.2", features = ["defmt"] }
embassy-time = { version = "0.4.0", features = ["defmt"] }
embedded-hal = "1.0.0"
esp-alloc = { version = "0.6.0", features = ["defmt"] }
esp-backtrace = { version = "0.15.0", features = [
    "defmt",
    "esp32c3",
    "exception-handler",
    "panic-handler",
] }
esp-hal = { version = "0.23.1", features = ["defmt", "esp32c3", "unstable"] }
esp-hal-embassy = { version = "0.6.0", features = ["defmt", "esp32c3"] }
esp-println = { version = "0.13.0", features = ["esp32c3", "log"] }
esp-wifi = { version = "0.12.0", default-features = false, features = [
    "ble",
    "builtin-scheduler",
    "defmt",
    "esp-alloc",
    "esp32c3",
] }
static_cell = "2.1.0"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false


[patch.crates-io]
esp-alloc       = { git = "https://github.com/esp-rs/esp-hal/", package = "esp-alloc", rev = "1a40e3419bb86f17e1a8bf93cb115c9df297b3ba" }
esp-backtrace   = { git = "https://github.com/esp-rs/esp-hal/", package = "esp-backtrace", rev = "1a40e3419bb86f17e1a8bf93cb115c9df297b3ba" }
esp-hal         = { git = "https://github.com/esp-rs/esp-hal/", package = "esp-hal", rev = "1a40e3419bb86f17e1a8bf93cb115c9df297b3ba" }
esp-hal-embassy = { git = "https://github.com/esp-rs/esp-hal/", package = "esp-hal-embassy", rev = "1a40e3419bb86f17e1a8bf93cb115c9df297b3ba" }
esp-println     = { git = "https://github.com/esp-rs/esp-hal/", package = "esp-println", rev = "1a40e3419bb86f17e1a8bf93cb115c9df297b3ba" }
esp-wifi        = { git = "https://github.com/esp-rs/esp-hal/", package = "esp-wifi", rev = "1a40e3419bb86f17e1a8bf93cb115c9df297b3ba" }
