[package]
authors = ["Sergio Gasquez <sergio.gasquez@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name    = "crimpdeq"
version = "0.1.0"

[dependencies]
bleps = { git = "https://github.com/bjoernQ/bleps", rev = "febf18abc4777b0227ef56b22aa6bcd78947fa24", package = "bleps", features = [
    "async",
    "defmt",
    "macros",
] }
bytemuck = "1.22.0"
bytemuck_derive = "1.8.1"
critical-section = "1.2.0"
defmt = "0.3.10"
defmt-rtt = "0.4.1"
embassy-executor = { version = "0.7.0", features = [
    "defmt",
    "task-arena-size-20480",
] }
embassy-sync = { version = "0.6.2", features = ["defmt"] }
embassy-time = { version = "0.4.0", features = ["defmt"] }
embedded-hal = "1.0.0"
embedded-io-async = "0.6.1"
embedded-storage = "0.3.1"
esp-alloc = { version = "0.7.0", features = ["defmt"] }
esp-backtrace = { version = "0.15.1", features = [
    "defmt",
    "esp32c3",
    "exception-handler",
    "panic-handler",
] }
esp-hal = { version = "1.0.0-beta.0", features = [
    "defmt",
    "esp32c3",
    "unstable",
] }
esp-hal-embassy = { version = "0.7.0", features = ["defmt", "esp32c3"] }
esp-println = { version = "0.13.1", features = ["esp32c3", "log"] }
esp-storage = { version = "0.5.0", features = ["esp32c3"] }
esp-wifi = { version = "0.13.0", default-features = false, features = [
    "ble",
    "builtin-scheduler",
    "defmt",
    "esp-alloc",
    "esp32c3",
] }
static_cell = "2.1.0"


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
