[package]
edition = "2021"
name    = "tindeq"
version = "0.1.0"

[[bin]]
name = "tindeq"
path = "./src/bin/main.rs"

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
bleps = { git = "https://github.com/bjoernQ/bleps", rev = "febf18abc4777b0227ef56b22aa6bcd78947fa24", package = "bleps", features = [
    "async",
    "defmt",
    "macros",
] }
bytemuck = "1.21.0"
bytemuck_derive = "1.8.1"
critical-section = "1.2.0"
defmt = "0.3.10"
defmt-rtt = "0.4.1"
embassy-executor = { version = "0.7.0", features = ["task-arena-size-20480"] }
embassy-futures = "0.1.1"
embassy-sync = "0.6.2"
embassy-time = "0.4.0"
embedded-io = "0.6.1"
esp-alloc = "0.6.0"
esp-backtrace = { version = "0.15.0", features = [
    "defmt",
    "esp32c3",
    "exception-handler",
    "panic-handler",
] }
esp-hal = { version = "0.23.1", features = ["esp32c3", "unstable"] }
esp-hal-embassy = { version = "0.6.0", features = ["esp32c3"] }
esp-println = { version = "0.13.0", features = ["esp32c3", "log"] }
esp-wifi = { version = "0.12.0", default-features = false, features = [
    "ble",
    "esp-alloc",
    "esp32c3",
    "log",
] }
heapless = { version = "0.8.0", default-features = false }
loadcell = { git = "https://github.com/DaneSlattery/hx711", rev = "8db73fe4884bbad7f3a88f2b40a821c3bfae2ee6" }
log = "0.4.21"
static_cell = { version = "2.1.0", features = ["nightly"] }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
