[alias]
bin = "espflash save-image --partition-table partition.csv --merge --flash-size 4mb --chip esp32c3 crimpdeq.bin"

[target.riscv32imc-unknown-none-elf]
runner = "probe-rs run --chip esp32c3 --no-location --preverify --idf-partition-table partition.csv"

[env]
DEFMT_LOG             = "off"             # Use "trace/debug/info/error" to enable defmt logging
DEVICE_ID             = "42"
DEVICE_NAME           = "Progressor_7125"
DEVICE_VERSION_NUMBER = "1.2.3.4"

# esp-wifi config
# This will allow sending data points up to 100 Hz
ESP_WIFI_CONFIG_TICK_RATE_HZ = "160"

[build]
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C",
  "force-frame-pointers",
  # Defmt support
  "-C",
  "link-arg=-Tdefmt.x",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
